import {observeTransport,appearance,openUtility,closeUtility} from './workbench_browser_helpers.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtemp, mkdir, readFile, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const root=await mkdtemp(path.join(tmpdir(),'buildmaster-offline-browser-'));
const artifacts='output/design-review/offline';await mkdir(artifacts,{recursive:true});
const launcher="import sys; from pathlib import Path; sys.path.insert(0,'scripts'); import surface_config; surface_config.ROOT=Path(sys.argv.pop(1)); import cnc_map_web; cnc_map_web.main()";
const server=spawn('python3',['-c',launcher,root,'--offline','--port','0'],{stdio:['ignore','pipe','pipe']});
let browser;
try {
 const url=await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{const m=String(d).match(/Open (http:\S+)/);if(m)resolve(m[1]);});server.once('exit',()=>reject(Error('Offline server exited')));});
 browser=await chromium.launch({channel:'chrome',headless:true});
 const first=await browser.newContext({viewport:{width:1440,height:960},colorScheme:'light'});
 const page=await first.newPage();const errors=[],writes=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('request',r=>{if(r.method()==='POST')writes.push(r.url().split('/').at(-1));});
 await observeTransport(page);await page.goto(url);await page.waitForFunction(()=>window.testTransport.state?.offline);
 await page.getByRole('heading',{name:'What are you making?'}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Start surface mapping',exact:true}).isDisabled(),true);
 assert.equal(await page.locator('#toolsWorkspace input').count(),0,'Optional tools should not mount until opened');
 await page.screenshot({path:artifacts+'/start-desktop.png'});
 await page.locator('#toolsTab').click();
 const tools=page.locator('#toolsWorkspace');
 for(const [name,value] of [['Minimum machine X (mm)','0'],['Maximum machine X (mm)','100'],['Minimum machine Y (mm)','0'],['Maximum machine Y (mm)','80'],['Minimum tip Z from material (mm)','-2'],['Maximum tip Z from material (mm)','30'],['Additional clearance margin (mm)','1']])await tools.getByRole('spinbutton',{name,exact:true}).fill(value);
 await tools.getByRole('button',{name:'Save fixture',exact:true}).click();
 await page.waitForFunction(()=>window.testTransport.job?.workflow.fixture&&!window.testTransport.pending);
 const fixtureDownload=page.waitForEvent('download');await tools.getByRole('button',{name:'Save job package',exact:true}).click();
 const fixture=JSON.parse(await readFile(await (await fixtureDownload).path(),'utf8'));
 assert.equal(fixture.files.length,0);assert.equal(fixture.job.workflow.fixture.bounds.x[1],100);
 await page.locator('#guideTab').click();await page.getByRole('button',{name:'Explore a geometry example'}).click();
 const replace=page.getByRole('alertdialog');await replace.waitFor();
 await replace.getByRole('button',{name:'Keep current job',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.testTransport.job.operations.length),0);
 await page.getByRole('button',{name:'Explore a geometry example'}).click();await replace.getByRole('button',{name:'Replace job',exact:true}).click();
 await page.getByRole('heading',{name:'Rectangle example'}).waitFor();
 await page.waitForFunction(()=>!window.testTransport.pending);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save job',exact:true}).click();
 const saved=JSON.parse(await readFile(await (await download).path(),'utf8'));
 assert.equal(saved.offline,true);assert.equal(saved.executionReleased,false);assert.equal(saved.job.canExport,false);
 assert.equal(saved.files.length,1);assert.equal(saved.job.alignment,null);
 assert.equal(JSON.stringify(saved).includes(url.split('#')[1]),false,'Secret in saved package');
 await page.locator('#pcbTab').click();await page.getByRole('tab',{name:'Alignment',exact:true}).click();
 assert.equal(await page.locator('#pcbCapture').isDisabled(),true);
 await page.getByRole('tab',{name:'UGS draft',exact:true}).click();assert.equal(await page.locator('#pcbExport').isDisabled(),true);
 await openUtility(page,'Workflow help');await page.getByRole('button',{name:'What happens in UGS?'}).click();
 await page.getByRole('link',{name:'UGS usage guide'}).waitFor();await closeUtility(page);
 // A new browser cannot silently take over an active owner.
 const second=await browser.newContext({viewport:{width:1440,height:960},colorScheme:'dark'});
 const recovered=await second.newPage();recovered.on('pageerror',e=>errors.push(String(e)));await observeTransport(recovered);await recovered.goto(url);
 await recovered.locator('.global-error').getByRole('button',{name:'Connection details'}).click();
 const recoverButton=recovered.getByRole('button',{name:'Recover closed tab & clear references',exact:true});
 await recoverButton.click();await recovered.getByText('The original tab is still active. Use it or close it before recovery.',{exact:true}).waitFor();
 await first.close();await recovered.waitForTimeout(3300);
 await recoverButton.click();await recovered.waitForFunction(()=>window.testTransport.state?.offline && window.testTransport.job?.operations.length===1 && !window.testTransport.pending);
 await closeUtility(recovered);assert.equal(await recovered.evaluate(()=>window.testTransport.state.armed),false);
 await recovered.screenshot({path:artifacts+'/recovered-desktop.png'});
 await recovered.setViewportSize({width:390,height:844});
 assert.equal(await recovered.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await recovered.screenshot({path:artifacts+'/recovered-mobile.png'});
 assert.equal(writes.some(a=>['arm','jog','jog-hold','scan','surface-import','pcb-export'].includes(a)),false);
 assert.deepEqual(errors,[]);
 console.log('Offline preparation passed: config-free start, fixture-only save, recovery packages, replacement protection, real job packages, machine locks, help and abandoned-tab ownership recovery. Disposable storage only.');
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 await rm(root,{recursive:true,force:true});
}
